language: cpp python

python: '2.7'

sudo: true

compiler:
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
      - g++-5
      - gcc-5

before_install:
  - sudo apt-get install libncurses-dev

install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="g++-5" CC="gcc-5"; fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - bin/tests